version: '3.1'

volumes:
  pg_project:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=courses_app
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - pg_project:/var/lib/postgresql/data
